#!/bin/bash

# ============================================================================                                                                                                     
# $Id$                                                                                                                                                                             
#                                                                                                                                                                                  
# $Revision$                                                                                                                                                                       
# $Date$                                                                                                                                                                           
# $LastChangedBy$                                                                                                                                                                  
# ============================================================================                                                                                                     
# DESCRIPTION                                                                                                                                                                      
# ============================================================================                                                                                                     
# PROJECT       : SenSyF                                                                                                                                                           
# COMPANY       : DEIMOS Engenharia S.A.                                                                                                                                           
# COMPONENT     : Streaming Executables                                                                                                                                            
# LANGUAGE      : Bash                                                                                                                                                             
# ----------------------------------------------------------------------------                                                                                                     
# PURPOSE                                                                                                                                                                          
#                                                                                                                                                                                  
# This file is the streaming executable for the Job 2 of SDK-TS-pilot 2.
# ========================================================================== #                                                                                                     

# source the ciop functions (e.g. ciop-log)
source ${ciop_job_include}

# define the exit codes
SUCCESS=0
ERR_NOINPUT=1
ERR_NOPARAMS=2
ERR_GDAL=4
ERR_COPY=5
ERR_PYTHON=6

# add a trap to exit gracefully
function cleanExit ()
{
   local retval=$?
   local msg="" 
   case "$retval" in
     $SUCCESS)      msg="Processing successfully concluded";;
     $ERR_NOPARAMS) msg="Outout format not defined";;
     $ERR_GDAL)    msg="Graph processing of job ${JOBNAME} failed (exit code $res)";;
     *)             msg="Unknown error";;
   esac
   [ "$retval" != "0" ] && ciop-log "ERROR" "Error $retval - $msg, processing aborted" || ciop-log "INFO" "$msg" 
   exit $retval
}
trap cleanExit EXIT

# add job1 executable to PATH
export PATH=/application/job_template_2/bin/:$PATH

# create the input directory
mkdir -p $TMPDIR/inputs/
export INPUTDIR=$TMPDIR/inputs/

# create rois directory
mkdir -p $TMPDIR/rois/
export rois_directory=$TMPDIR/rois/

# create the output directory
mkdir -p $TMPDIR/outputs/
export OUTPUTDIR=$TMPDIR/outputs/

#read inputs
while read inputs_from_previous_job
    do
        # split the tuple (outputs from the previous jobs are tuples)                                                                                                              
        kml_folder=`echo $inputs_from_previous_job | cut -d, -f2`
        product_url=`echo $inputs_from_previous_job | cut -d, -f1`

	ciop-log "INFO" "ciop-copy -f o inputurls $INPUTDIR"
	INPUTPRODUCT=`ciop-copy -f -o $INPUTDIR $product_url` >/dev/null
	[ "$?" == "0" ] || exit $ERR_COPY
	ROISDIR=`ciop-copy -f -o $rois_directory $kml_folder` >/dev/null
	[ "$?" == "0" ] || exit $ERR_COPY

	JOB2 $INPUTPRODUCT $ROISDIR $OUTPUTDIR
	[ "$?" == "0" ] || exit $ERR_PYTHON

	# compress the output                                                                                                                                                      
	product_name=`basename $INPUTPRODUCT`
	rois_folder=`basename $ROISDIR`
	output_name="${product_name}_$rois_folder"
        cd $OUTPUTDIR
        tar cvzf $OUTPUTDIR/$output_name.tar.gz $output_name

        # publish outputs                                                                                                                                                          
        ciop-publish $OUTPUTDIR/$output_name.tar.gz

	# clean output directory
	rm -rf $OUTPUTDIR/*
    done
